# Generated by Django 5.2.12 on 2026-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='shelters/'),
        ),
    ]
