# Generated by Django 5.2.12 on 2026-05-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_adopterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('completed', 'Completed')], default='submitted', max_length=20),
        ),
    ]
