# Generated by Django 5.2.12 on 2026-05-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_favoritepet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
