# Generated by Django 5.2.12 on 2026-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_pet_archived_at_pet_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shelter',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
