# Generated by Django 5.2.12 on 2026-05-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_shelter_barangay_shelter_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adoption_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccination_status',
            field=models.CharField(blank=True, default='Fully Vaccinated', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
